name: Build and Release

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: macos-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      
      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      
      - name: Get Version
        id: get_version
        run: echo "VERSION=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV
      
      - name: Setup GitHub CLI
        run: gh auth setup-git --token ${{ secrets.GITHUB_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Create Release and Upload Asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}
        run: |
          # Verificar que el ejecutable existe
          if [ ! -f "./target/release/rust-3d-printing-calculator" ]; then
            echo "Error: El ejecutable no se encuentra en la ruta esperada"
            ls -la ./target/release/
            exit 1
          fi
          
          # Renombrar el ejecutable para que tenga un nombre más descriptivo
          cp ./target/release/rust-3d-printing-calculator ./target/release/printing-cost-calculator-macos
          
          # Crear release y subir el asset usando gh CLI
          gh release create "v$VERSION" \
            --title "Release v$VERSION" \
            --notes "Automated build for macOS" \
            ./target/release/printing-cost-calculator-macos